BEGIN TRANSACTION

CREATE TABLE USER_DATA (
USER_USERID				VARCHAR(6)	PRIMARY KEY,
USER_USERNAME			VARCHAR(20) NOT NULL,
USER_PASSWORD			VARCHAR(20) NOT NULL,
USER_FNAME				VARCHAR(40) NOT NULL,
USER_LNAME				VARCHAR(40) NOT NULL,
USER_EMAIL_ADDRESS		VARCHAR(50) NOT NULL,
IS_ADMIN				TINYINT		NOT NULL,		/* 0 for false 1 for true */
IS_USER_LOGGEDIN		TINYINT		NOT NULL);		/* 0 for false 1 for true */


CREATE TABLE VIDEO_DATA (
VIDEO_ID				VARCHAR(6)	PRIMARY KEY,
VIDEO_NAME				VARCHAR(80)	NOT NULL,
VIDEO_VIEWS				VARCHAR(10) NOT NULL,
VIDEO_DATE				DATE		NOT NULL,
VIDEO_UPVOTES			INT		    NOT NULL,
VIDEO_DOWNVOTES			INT			NOT NULL,
USER_USERID				VARCHAR(6) FOREIGN KEY REFERENCES USER_DATA(USER_USERID));

CREATE TABLE VIDEO_RANKINGS (
RANKING_ID				VARCHAR(6) PRIMARY KEY,
RANKING_STORYTELLING	INT			NOT NULL,
RANKING_CINEMATOGRAPHY	INT			NOT NULL,
RANKING_ORIGININALITY	INT			NOT NULL,
RANKING_DIALOGUE		INT			NOT NULL,
RANKING_CHARACTER_DEV	INT			NOT NULL,
VIDEO_ID				VARCHAR(6) FOREIGN KEY REFERENCES VIDEO_DATA(VIDEO_ID));

INSERT INTO USER_DATA (USER_USERID, USER_USERNAME, USER_PASSWORD, USER_FNAME, USER_LNAME, USER_EMAIL_ADDRESS, IS_ADMIN, IS_USER_LOGGEDIN)
VALUES(000001, 'Overlord408', 'Evildarck2', 'Brandon', 'Mayhue', 'brandonmayhueis@yourmomshouse.com', 1, 0),
(000002, 'GuitarSolo2', 'RocknRoll314', 'Isaac', 'Shuppas', 'pissinshoe@goldenshowers.com', 1, 0),
(000003, 'DMagazine89', 'Ireadstuff2', 'David', 'Magazine', 'dm@gmail.com', 1, 0);

INSERT INTO VIDEO_DATA (VIDEO_ID, VIDEO_NAME, VIDEO_VIEWS, VIDEO_DATE, VIDEO_UPVOTES, VIDEO_DOWNVOTES, USER_USERID)
VALUES (100001, 'The tale of golden needle films', 42, '1-15-2017', 50, 100, 000001);

SELECT COUNT(USER_USERNAME) FROM USER_DATA;

SELECT USER_USERNAME FROM USER_DATA;

SELECT VIDEO_DATE, VIDEO_NAME, VIDEO_UPVOTES, VIDEO_DOWNVOTES, VIDEO_VIEWS FROM VIDEO_DATA;

SELECT RANKING_STORYTELLING, RANKING_CINEMATOGRAPHY, RANKING_ORIGININALITY, RANKING_DIALOGUE, RANKING_CHARACTER_DEV FROM VIDEO_RANKINGS;

/* THIS IS HOW YOU DO PERCENTAGES!!!!!! */
SELECT CAST(CAST(VIDEO_UPVOTES AS decimal) / CAST(VIDEO_DOWNVOTES AS decimal) * 100 AS int) from VIDEO_DATA AS PERCENTAGE;